FROM node:15.14.0-alpine

COPY package*.json /
RUN npm install
COPY /backend/ /backend/

WORKDIR /frontend
COPY package*.json /frontend/
RUN npm install
COPY /frontend/ /frontend/
RUN REACT_APP_ENV=demo npm run build

WORKDIR /
EXPOSE 5000
VOLUME /logs

ENV COMPOSE_VERSION=${COMPOSE_VERSION}
ENV NODE_ENV=${NODE_ENV}

ENV PORT=${PORT}
ENV JWT_SECRET=${JWT_SECRET}
ENV GMAIL_HOST=${GMAIL_HOST}
ENV GMAIL_PORT=${GMAIL_PORT}
ENV GMAIL_USER=${GMAIL_USER}
ENV GMAIL_PASS=${GMAIL_PASS}
ENV AZ_APPLICATION_ID=${AZ_APPLICATION_ID}
ENV AZ_LOCATAIRE_ID=${AZ_LOCATAIRE_ID}
ENV AZ_SECRET=${AZ_SECRET}
ENV AZ_REDIRECT_URI=${AZ_REDIRECT_URI}

ENV DOMAIN_NAME_POC=${DOMAIN_NAME_POC}
ENV DOMAIN_NAME_DEMO=${DOMAIN_NAME_DEMO}
ENV DOMAIN_NAME_DEV=${DOMAIN_NAME_DEV}
ENV DOMAIN_NAME_DOCKER=${DOMAIN_NAME_DOCKER}

# MONGO environement variables when NODE_ENV=poc -----------
ENV MONGO_URI_POC=${MONGO_URI_POC}
ENV MONGO_URI_DEMO=${MONGO_URI_DEMO}
ENV MONGO_URI_DOCKER=${MONGO_URI_DOCKER}
ENV MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
ENV MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
ENV MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

ENV ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER}
ENV ME_CONFIG_MONGODB_ENABLE_ADMIN=${ME_CONFIG_MONGODB_ENABLE_ADMIN}
ENV ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
ENV ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
ENV ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
ENV ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}

ENV MONGO_TARGET=${MONGO_TARGET}

CMD npm start