export const TACE_CREATE_REQUEST = 'TACE_CREATE_REQUEST';
export const TACE_CREATE_SUCCESS = 'TACE_CREATE_SUCCESS';
export const TACE_CREATE_FAIL = 'TACE_CREATE_FAIL';
export const TACE_CREATE_RESET = 'TACE_CREATE_RESET';