export const ACCESS_LIST_REQUEST = 'ACCESS_LIST_REQUEST';
export const ACCESS_LIST_SUCCESS = 'ACCESS_LIST_SUCCESS';
export const ACCESS_LIST_FAIL = 'ACCESS_LIST_FAIL';
export const ACCESS_LIST_RESET = 'ACCESS_LIST_RESET';

export const ACCESS_UPDATE_FRONTACCESS_REQUEST = 'ACCESS_UPDATE_FRONTACCESS_REQUEST';
export const ACCESS_UPDATE_FRONTACCESS_SUCCESS = 'ACCESS_UPDATE_FRONTACCESS_SUCCESS';
export const ACCESS_UPDATE_FRONTACCESS_FAIL = 'ACCESS_UPDATE_FRONTACCESS_FAIL';
export const ACCESS_UPDATE_FRONTACCESS_RESET = 'ACCESS_UPDATE_FRONTACCESS_RESET';

export const ACCESS_MODES = ['no', 'yes', 'read', 'write'];
export const ACCESS_DATAS = ['my', 'team', 'department', 'domain', 'all'];