export const ACCESS_LIST_REQUEST = 'ACCESS_LIST_REQUEST';
export const ACCESS_LIST_SUCCESS = 'ACCESS_LIST_SUCCESS';
export const ACCESS_LIST_FAIL = 'ACCESS_LIST_FAIL';
export const ACCESS_LIST_RESET = 'ACCESS_LIST_RESET';