export const CLIENT_ALL_REQUEST = 'CLIENT_ALL_REQUEST';
export const CLIENT_ALL_SUCCESS = 'CLIENT_ALL_SUCCESS';
export const CLIENT_ALL_FAIL = 'CLIENT_ALL_FAIL';
export const CLIENT_ALL_RESET = 'CLIENT_ALL_RESET';

export const CLIENT_CREATE_REQUEST = 'CLIENT_CREATE_REQUEST';
export const CLIENT_CREATE_SUCCESS = 'CLIENT_CREATE_SUCCESS';
export const CLIENT_CREATE_FAIL = 'CLIENT_CREATE_FAIL';
export const CLIENT_CREATE_RESET = 'CLIENT_CREATE_RESET';

export const CLIENT_UPDATE_REQUEST = 'CLIENT_UPDATE_REQUEST';
export const CLIENT_UPDATE_SUCCESS = 'CLIENT_UPDATE_SUCCESS';
export const CLIENT_UPDATE_FAIL = 'CLIENT_UPDATE_FAIL';
export const CLIENT_UPDATE_RESET = 'CLIENT_UPDATE_RESET';