export const DEAL_CREATE_REQUEST = 'DEAL_CREATE_REQUEST';
export const DEAL_CREATE_SUCCESS = 'DEAL_CREATE_SUCCESS';
export const DEAL_CREATE_FAIL = 'DEAL_CREATE_FAIL';
export const DEAL_CREATE_RESET = 'DEAL_CREATE_RESET';

export const DEAL_UPDATE_REQUEST = 'DEAL_UPDATE_REQUEST';
export const DEAL_UPDATE_SUCCESS = 'DEAL_UPDATE_SUCCESS';
export const DEAL_UPDATE_FAIL = 'DEAL_UPDATE_FAIL';
export const DEAL_UPDATE_RESET = 'DEAL_UPDATE_RESET';

export const DEAL_ALL_LIST_REQUEST = 'DEAL_ALL_LIST_REQUEST';
export const DEAL_ALL_LIST_SUCCESS = 'DEAL_ALL_LIST_SUCCESS';
export const DEAL_ALL_LIST_FAIL = 'DEAL_ALL_LIST_FAIL';
export const DEAL_ALL_LIST_RESET = 'DEAL_ALL_LIST_RESET';

export const DEAL_DELETE_REQUEST = 'DEAL_DELETE_REQUEST';
export const DEAL_DELETE_SUCCESS = 'DEAL_DELETE_SUCCESS';
export const DEAL_DELETE_FAIL = 'DEAL_DELETE_FAIL';
export const DEAL_DELETE_RESET = 'DEAL_DELETE_RESET';

export const DEAL_EDIT_REQUEST = 'DEAL_EDIT_REQUEST';
export const DEAL_EDIT_SUCCESS = 'DEAL_EDIT_SUCCESS';
export const DEAL_EDIT_FAIL = 'DEAL_EDIT_FAIL';
export const DEAL_EDIT_RESET = 'DEAL_EDIT_RESET';