export const DEAL_CREATE_REQUEST = 'DEAL_CREATE_REQUEST';
export const DEAL_CREATE_SUCCESS = 'DEAL_CREATE_SUCCESS';
export const DEAL_CREATE_FAIL = 'DEAL_CREATE_FAIL';
export const DEAL_CREATE_RESET = 'DEAL_CREATE_RESET';