export const DEAL_CREATE_REQUEST = 'DEAL_CREATE_REQUEST';
export const DEAL_CREATE_SUCCESS = 'DEAL_CREATE_SUCCESS';
export const DEAL_CREATE_FAIL = 'DEAL_CREATE_FAIL';
export const DEAL_CREATE_RESET = 'DEAL_CREATE_RESET';

export const DEAL_ALL_LIST_REQUEST = 'DEAL_ALL_LIST_REQUEST';
export const DEAL_ALL_LIST_SUCCESS = 'DEAL_ALL_LIST_SUCCESS';
export const DEAL_ALL_LIST_FAIL = 'DEAL_ALL_LIST_FAIL';
export const DEAL_ALL_LIST_RESET = 'DEAL_ALL_LIST_RESET';