export const PXX_GET_MONTH_INFO_REQUEST = 'PXX_GET_MONTH_REQUEST';
export const PXX_GET_MONTH_INFO_SUCCESS = 'PXX_GET_MONTH_SUCCESS';
export const PXX_GET_MONTH_INFO_FAIL = 'PXX_GET_MONTH_FAIL';
export const PXX_GET_MONTH_INFO_RESET = 'PXX_GET_MONTH_RESET';

export const PXX_LIST_REQUEST = 'PXX_GET_ALL_REQUEST';
export const PXX_LIST_SUCCESS = 'PXX_GET_ALL_SUCCESS';
export const PXX_LIST_FAIL = 'PXX_GET_ALL_FAIL';
export const PXX_LIST_RESET = 'PXX_GET_ALL_RESET';