export const PXX_MY_TO_EDIT_REQUEST = 'PXX_MY_TO_EDIT_REQUEST';
export const PXX_MY_TO_EDIT_SUCCESS = 'PXX_MY_TO_EDIT_SUCCESS';
export const PXX_MY_TO_EDIT_FAIL = 'PXX_MY_TO_EDIT_FAIL';
export const PXX_MY_TO_EDIT_RESET = 'PXX_MY_TO_EDIT_RESET';

export const PXX_UPDATE_REQUEST = 'PXX_UPDATE_REQUEST';
export const PXX_UPDATE_SUCCESS = 'PXX_UPDATE_SUCCESS';
export const PXX_UPDATE_FAIL = 'PXX_UPDATE_FAIL';
export const PXX_UPDATE_RESET = 'PXX_UPDATE_RESET';

export const PXX_LIST_REQUEST = 'PXX_LIST_REQUEST';
export const PXX_LIST_SUCCESS = 'PXX_LIST_SUCCESS';
export const PXX_LIST_FAIL = 'PXX_LIST_FAIL';
export const PXX_LIST_RESET = 'PXX_LIST_RESET';

export const PXX_USER_LIST_REQUEST = 'PXX_USER_LIST_REQUEST';
export const PXX_USER_LIST_SUCCESS = 'PXX_USER_LIST_SUCCESS';
export const PXX_USER_LIST_FAIL = 'PXX_USER_LIST_FAIL';
export const PXX_USER_LIST_RESET = 'PXX_USER_LIST_RESET';