export const PXX_MY_TO_EDIT_REQUEST = 'PXX_MY_TO_EDIT_REQUEST';
export const PXX_MY_TO_EDIT_SUCCESS = 'PXX_MY_TO_EDIT_SUCCESS';
export const PXX_MY_TO_EDIT_FAIL = 'PXX_MY_TO_EDIT_FAIL';
export const PXX_MY_TO_EDIT_RESET = 'PXX_MY_TO_EDIT_RESET';

export const PXX_UPDATE_REQUEST = 'PXX_UPDATE_REQUEST';
export const PXX_UPDATE_SUCCESS = 'PXX_UPDATE_SUCCESS';
export const PXX_UPDATE_FAIL = 'PXX_UPDATE_FAIL';
export const PXX_UPDATE_RESET = 'PXX_UPDATE_RESET';

export const PXX_LIST_REQUEST = 'PXX_LIST_REQUEST';
export const PXX_LIST_SUCCESS = 'PXX_LIST_SUCCESS';
export const PXX_LIST_FAIL = 'PXX_LIST_FAIL';
export const PXX_LIST_RESET = 'PXX_LIST_RESET';

export const PXX_USER_LIST_REQUEST = 'PXX_USER_LIST_REQUEST';
export const PXX_USER_LIST_SUCCESS = 'PXX_USER_LIST_SUCCESS';
export const PXX_USER_LIST_FAIL = 'PXX_USER_LIST_FAIL';
export const PXX_USER_LIST_RESET = 'PXX_USER_LIST_RESET';

export const PXX_TACE_REQUEST = 'PXX_TACE_REQUEST';
export const PXX_TACE_SUCCESS = 'PXX_TACE_SUCCESS';
export const PXX_TACE_FAIL = 'PXX_TACE_FAIL';
export const PXX_TACE_RESET = 'PXX_TACE_RESET';

export const PXX_AVAILABILITIES_REQUEST = 'PXX_AVAILABILITIES_REQUEST';
export const PXX_AVAILABILITIES_SUCCESS = 'PXX_AVAILABILITIES_SUCCESS';
export const PXX_AVAILABILITIES_FAIL = 'PXX_AVAILABILITIES_FAIL';
export const PXX_AVAILABILITIES_RESET = 'PXX_AVAILABILITIES_RESET';

export const PXX_ALL_REQUEST = 'PXX_ALL_REQUEST';
export const PXX_ALL_SUCCESS = 'PXX_ALL_SUCCESS';
export const PXX_ALL_FAIL = 'PXX_ALL_FAIL';
export const PXX_ALL_RESET = 'PXX_ALL_RESET';

export const PXX_IMPORT_MASS_REQUEST = 'PXX_IMPORT_MASS_REQUEST';
export const PXX_IMPORT_MASS_SUCCESS = 'PXX_IMPORT_MASS_SUCCESS';
export const PXX_IMPORT_MASS_FAIL = 'PXX_IMPORT_MASS_FAIL';
export const PXX_IMPORT_MASS_RESET = 'PXX_IMPORT_MASS_RESET';

export const PXX_IMPORT_LINE_REQUEST = 'PXX_IMPORT_LINE_REQUEST';
export const PXX_IMPORT_LINE_SUCCESS = 'PXX_IMPORT_LINE_SUCCESS';
export const PXX_IMPORT_LINE_FAIL = 'PXX_IMPORT_LINE_FAIL';
export const PXX_IMPORT_LINE_RESET = 'PXX_IMPORT_LINE_RESET';

export const PXX_UPLOAD_FILE_REQUEST = 'PXX_UPLOAD_FILE_REQUEST';
export const PXX_UPLOAD_FILE_SUCCESS = 'PXX_UPLOAD_FILE_SUCCESS';
export const PXX_UPLOAD_FILE_FAIL = 'PXX_UPLOAD_FILE_FAIL';
export const PXX_UPLOAD_FILE_RESET = 'PXX_UPLOAD_FILE_RESET';