export const SKILL_LIST_REQUEST = 'SKILL_LIST_REQUEST';
export const SKILL_LIST_SUCCESS = 'SKILL_LIST_SUCCESS';
export const SKILL_LIST_FAIL = 'SKILL_LIST_FAIL';
export const SKILL_LIST_RESET = 'SKILL_LIST_RESET';

export const SKILL_DELETE_REQUEST = 'SKILL_DELETE_REQUEST';
export const SKILL_DELETE_SUCCESS = 'SKILL_DELETE_SUCCESS';
export const SKILL_DELETE_FAIL = 'SKILL_DELETE_FAIL';
export const SKILL_DELETE_RESET = 'SKILL_DELETE_RESET';

export const SKILL_CREATE_REQUEST = 'SKILL_CREATE_REQUEST';
export const SKILL_CREATE_SUCCESS = 'SKILL_CREATE_SUCCESS';
export const SKILL_CREATE_FAIL = 'SKILL_CREATE_FAIL';
export const SKILL_CREATE_RESET = 'SKILL_CREATE_RESET';